// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PixelLab.Mac.Demo
{


	// Should subclass MonoMac.AppKit.NSWindow
	[MonoMac.Foundation.Register("MainWindow")]
	public partial class MainWindow
	{

		private global::MonoMac.AppKit.NSTextField __mt_clickCountText;

		#pragma warning disable 0169
		[MonoMac.Foundation.Connect("clickCountText")]
		private global::MonoMac.AppKit.NSTextField clickCountText {
			get {
				this.__mt_clickCountText = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField ("clickCountText")));
				return this.__mt_clickCountText;
			}
			set {
				this.__mt_clickCountText = value;
				this.SetNativeField ("clickCountText", value);
			}
		}
	}

	// Should subclass MonoMac.AppKit.NSWindowController
	[MonoMac.Foundation.Register("MainWindowController")]
	public partial class MainWindowController
	{

		private global::MonoMac.AppKit.NSActionCell __mt_ClickCountLabel;

		#pragma warning disable 0169
		[MonoMac.Foundation.Export("ButtonClick:")]
		partial void ButtonClick (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Connect("ClickCountLabel")]
		private global::MonoMac.AppKit.NSActionCell ClickCountLabel {
			get {
				this.__mt_ClickCountLabel = ((global::MonoMac.AppKit.NSActionCell)(this.GetNativeField ("ClickCountLabel")));
				return this.__mt_ClickCountLabel;
			}
			set {
				this.__mt_ClickCountLabel = value;
				this.SetNativeField ("ClickCountLabel", value);
			}
		}
	}
}
